//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinaShopV2.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TinaShopV2.App_GlobalResources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy sản phẩm, hoặc hệ thống có vấn đề..
        /// </summary>
        public static string CanNotSearch {
            get {
                return ResourceManager.GetString("CanNotSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu bạn yêu cầu không tồn tại..
        /// </summary>
        public static string DataNotExisting {
            get {
                return ResourceManager.GetString("DataNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu &apos;{0}&apos; bạn yêu cầu không tồn tại..
        /// </summary>
        public static string DataNotExisting_FormatName {
            get {
                return ResourceManager.GetString("DataNotExisting_FormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu truyền vào không thể rỗng..
        /// </summary>
        public static string DataNotNull {
            get {
                return ResourceManager.GetString("DataNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; đã tồn tại..
        /// </summary>
        public static string FieldExisting {
            get {
                return ResourceManager.GetString("FieldExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập vào trang này, vui lòng đăng nhập với 1 tài khoản khác!.
        /// </summary>
        public static string Http401 {
            get {
                return ResourceManager.GetString("Http401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng sử dụng những hình ảnh có định dạng &quot; .jpg, .png, .gif, .bmp &quot;.
        /// </summary>
        public static string ImageExtension {
            get {
                return ResourceManager.GetString("ImageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu tiền tệ không hợp lệ..
        /// </summary>
        public static string InvalidCurrency {
            get {
                return ResourceManager.GetString("InvalidCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; không được dài quá {1} ký tự..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thay đổi loại Menu..
        /// </summary>
        public static string NotChangeMenuType {
            get {
                return ResourceManager.GetString("NotChangeMenuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa đối tượng này, vì đang có liên kết với dữ liệu khác..
        /// </summary>
        public static string NotDelete_HaveChild {
            get {
                return ResourceManager.GetString("NotDelete_HaveChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể chọn giá trị này..
        /// </summary>
        public static string NotSelectThisValue {
            get {
                return ResourceManager.GetString("NotSelectThisValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; không thể chọn giá trị này..
        /// </summary>
        public static string NotSelectThisValueFormat {
            get {
                return ResourceManager.GetString("NotSelectThisValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang bạn yêu cầu không tồn tại..
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập &apos;{0}&apos;.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; có giá trị phải nằm trong khoảng &apos;{1}&apos; - &apos;{2}&apos;.
        /// </summary>
        public static string ValueBetween {
            get {
                return ResourceManager.GetString("ValueBetween", resourceCulture);
            }
        }
    }
}
